In [16]:
import pandas as pd
import numpy as np
import math

## Reading stock price data from a file

In [24]:
df = pd.read_excel("./ukx.xlsx")
df = df.dropna(axis=1)
df = df.iloc[1:, [0, 1, 3]]
df.columns = ["date", "Acme", "BigBank"]
Acme = df["Acme"].to_list()

f = lambda x: math.log(math.pi, x)
Acme = list(map(f, Acme))
BigBank = df["BigBank"].to_list()
BigBank = list(map(f, BigBank))
df["Acme"] = Acme
df["BigBank"] = BigBank
df

date      Acme   BigBank
1    2000-02-25 00:00:00  0.171864  0.195631
2    2000-03-03 00:00:00  0.171924  0.194526
3    2000-03-10 00:00:00  0.173146  0.195872
4    2000-03-17 00:00:00  0.172769  0.194138
5    2000-03-24 00:00:00  0.171560  0.190103
..                   ...       ...       ...
730  2014-02-14 00:00:00  0.156253  0.144143
731  2014-02-21 00:00:00  0.155687  0.143019
732  2014-02-28 00:00:00  0.156092  0.142989
733  2014-03-07 00:00:00  0.157073  0.143163
734  2014-03-14 00:00:00  0.157665  0.143988

[734 rows x 3 columns]

###### Create a matrix call dZ 

In [39]:
result = []
for i in range(1, len(df), 1):
    c = list()
    a = df.iloc[1, 1] - df.iloc[0, 1]
    b = df.iloc[1, 2] - df.iloc[0, 2]
    c.append(a)
    c.append(b)
    result.append(c)
dZ = np.array(result)
dZ

array([[ 5.96184175e-05, -1.10470547e-03],
       [ 5.96184175e-05, -1.10470547e-03],
       [ 5.96184175e-05, -1.10470547e-03],
       ...,
       [ 5.96184175e-05, -1.10470547e-03],
       [ 5.96184175e-05, -1.10470547e-03],
       [ 5.96184175e-05, -1.10470547e-03]])

The sample average value of the vector

In [43]:
m = np.mean(dZ, axis=0)
m

array([ 5.96184175e-05, -1.10470547e-03])

The sample convarianc matrix for the change.

In [48]:
sigma = np.cov(dZ.T)
sigma

array([[0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 3.64618563e-34]])

## Simulating stock prices

In [53]:
simulated_S = np.random.multivariate_normal(m , sigma, size=10 ** 6)
simulated_S

array([[ 5.96184175e-05, -1.10470547e-03],
       [ 5.96184175e-05, -1.10470547e-03],
       [ 5.96184175e-05, -1.10470547e-03],
       ...,
       [ 5.96184175e-05, -1.10470547e-03],
       [ 5.96184175e-05, -1.10470547e-03],
       [ 5.96184175e-05, -1.10470547e-03]])

## Historic volatility

In [66]:
hostoric_volatility = (sigma.diagonal().sum() / 52) ** 0.5
print("Historic volatility is:")
hostoric_volatility

Historic volatility is:


2.6479983853867666e-18

## Computing option prices

In [58]:
def black_scholes_call_price(S0, K, T, r, sigma):
    d1 = (np.log(S / K) + (r + 0.5 * sigma ** 2) * T) / (sigma * np.sqrt(T))
    d2 = (np.log(S/K) + (r - 0.5*sigma**2)*T)/(sigma * np.sqrt(T))
    p = (S * norm.cdf(d1, 0.0, 1.0) - K*np.exp(-r*T)*norm.cdf(d2, 0.0, 1.0))
    if p:
        return p

    raise NotImplementedError

In [60]:
import numpy as np
a=np.array([[1.123,2.123,3.123],[4.456,5.456,6.456],[7.789,8.789,9.789]])
a


array([[1.123, 2.123, 3.123],
       [4.456, 5.456, 6.456],
       [7.789, 8.789, 9.789]])

In [62]:
a.diagonal()

array([1.123, 5.456, 9.789])